name: Build ZMK firmware
on: [workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    # uses: AmmarAbouZor/zmk/.github/workflows/build-user-config.yml@keychron_bpro
